### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by panios** [wesslen/topicApp#6]
Thank you the app looks really neat, but I am getting two errors : 1) ERROR: [on_request_read] connection reset by peer, 2) Warning: Error in validObject: invalid class “dfmSparse” object: superclass "replValueSp" not defined in the environment of the object's class

**Comment by wesslen** [comment]
Thanks PanosKostakos. Can you give me more details?

Were you able to install all of the libraries? You can test them by calling them (e.g. library(d3wordcloud) ) to make sure they're running.

**Comment by panios** [comment]
I reinstalled "quanteda" and works now.

**Comment by wesslen** [comment]
Great! Thanks for the heads up. I'll put a note as it requires the newest version of quanteda
