### ISSUE TITLE
Question about number of topic and usage of tool

### ISSUE THREAD

**Issue by drdadkhah** [wesslen/topicApp#7]
Hi,
I used Your interested Shiny app. It is very good. I have two questions:
1-Please see [this image](https://pasteboard.co/JyN6lOv.jpg) , what is best number of topic for my data?
2- Can i use your tool to analyze my data and publish my result as the academic paper? I will cite your source code in Github. 
Many thanks!

**Comment by wesslen** [comment]
Hi-glad it can help. I'll be honest if I had time/support there's a ton more I'd do now.

1. See the original [STM documentation](https://github.com/bstewart/stm/blob/master/vignettes/stmVignette.pdf?raw=true)

The key problem is remember this is unsupervised ML. Everyone new to this brings prior beliefs/expectations that there should be a simple heuristic (e.g., max semantic coherence, etc) but the unfortunate reality is this is more of an art than a science. What's important is to learn what each of these measures mean and to connect that to what you're trying to accomplish. For example, choosing K that maximizes the held-out-likelihood would be choosing the K model that best fits the data. However, choosing the model that has the best semantic coherence may lead to the most "interpretable/consistent topics", which may not be the same as the best K from held-out likelihood.

If you're interested in learning more (or more in depth about STM, etc), consider my arxiv (phd qualifier paper) https://arxiv.org/pdf/1803.11045.pdf

2. If you use this app, please cite:
Banks, G. C., Woznyj, H. M., Wesslen, R. S., & Ross, R. L. (2018). A review of best practice recommendations for text analysis in R (and a user-friendly app). Journal of Business and Psychology, 33(4), 445-459.

This paper references this app.

In addition, if you find my arxiv paper helpful, you can cite that too:
Wesslen, R. (2018). Computer-assisted text analysis for social science: Topic models and beyond. arXiv preprint arXiv:1803.11045.

Hope this helps!
