### ISSUE TITLE
Error `%AND%` shiny

### ISSUE THREAD

**Issue by Woprates** [wesslen/topicApp#8]
Hello there....show up the following error.

 Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object '%AND%' not found. 

Such function is in directoryInput.R file. 

Best regards

**Comment by wesslen** [comment]
This package is deprecated and package dependencies have been broken. You’re welcome to do a PR request to fix. Problem is there weren’t good ways of making the package robust to package issues when it was created like Docker or renv.
